[alias]
try = "run --release --bin search -- data/ciphertext/all-original.csv pt(0,0)==pt(1,0) arx --sequential"
try-debug = "run --bin search -- data/ciphertext/all-original.csv pt(0,0)==pt(1,0) arx --sequential"
try-parallel = "run --release --bin search -- data/ciphertext/all-original.csv pt(0,0)==pt(1,0) arx"
try-parallel-debug = "run --bin search -- data/ciphertext/all-original.csv pt(0,0)==pt(1,0) arx"