[alias]
try = "run --release --bin search -- data/ciphertext/all-original.csv arx --sequential"
try-debug = "run --bin search -- data/ciphertext/all-original.csv arx --sequential"
try-parallel = "run --release --bin search -- data/ciphertext/all-original.csv arx"
try-parallel-debug = "run --bin search -- data/ciphertext/all-original.csv arx"